server:
  port: 8011
#配置SSL自定义证书，实现访问https
  ssl:
    key-store: classpath:.keystore
    key-store-password: 123456
    key-store-type: JKS
    key-alias: nick.keystore

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db
    userName: root
    password: root
#  redis:
#    host: localhost
#    port: 6379
#    timeout: 20000
  mail:
    host: smtp.sina.cn
    port: 25
    protocol: smtp
    default-encoding: UTF-8
    username: xxx@sina.com
    password: xxx

profiles:
  active: ${profiles.actives}

# 集成mybatis
mybatis:
    type-aliases-package: com.nick.mapper
    mapper-locations: classpath:mapper/*.xml

hello:
  msg: Nick
debug: false
