server:
  port: 8011

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://47.98.171.112:3306/ele-zb
    userName: root
    password: tiger
  redis:
    host: localhost
    port: 6379
    timeout: 20000

profiles:
  active: ${profiles.actives}

# 集成mybatis
mybatis:
    type-aliases-package: com.nick.mapper
    mapper-locations: classpath:mapper/*.xml
